// <auto-generated />
namespace Parking.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecc));
        
        string IMigrationMetadata.Id
        {
            get { return "201709081353189_updatecc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
